spring:
  profiles:
    active: dev
  application:
    name: diary
  messages:
    encoding: UTF-8
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/diary?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
    # 每次启动更改数据表结构
    hibernate:
      ddl-auto: update

server:
  tomcat:
    uri-encoding: UTF-8
  port: 16602
  servlet:
    context-path: /diary

